di/direction.go

I keep finding places where I need to choose something based on the axis of text, and the ergonomics of doing that right now are pretty bad. This commit introduces the constants for expressing vertical text and an easy way to look up the axis of text.
I'm open to other ways of doing this if you see alternatives.

di: define vertical directions and axis helper

---

.github/workflows/test.yml

I figured it would be nice to have a little CI. This is just a really basic config. I based it off of [this](https://github.com/mvdan/github-actions-golang), but I removed platforms and go versions that are probably overkill as testing targets. Right now, the fact that it's a matrix build does us no good, but leaving that structure would make it easy to insert new testing go versions and OSes if we wanted to. I don't mind pulling it out though.

ci: add basic compilation and test running to CI

---

shaping/output.go
shaping/output_test.go
shaping/shaper.go

With #12 merged, we can simplify the Output.{RecomputeAdvance, RecalculateAll} signatures.
(This is safe because we never wan't to use a different direction than the once used to shape the input.)

Clean the recompute API

---

di/direction.go

This commit introduces a type that represents how a piece
of text is read relative to the origin as well as a
method to get the progression from any direction.
This information makes it easy to write algorithms that
operate on text of only one progression, but across any
axis.
Closes #14
Signed-off-by: Chris Waldon <christopher.waldon.dev@gmail.com>

di: add text progression types and method

---

shaping/input.go
shaping/input_test.go

One of my main motivation to discuss #17 is that I initially thought the shaping API would have to know about font descriptions to support the general capabilities I need. 
I now realize that it actually only requires a small addition to the shaping package. With this PR, the font index mechanism described in #17 may then entirely be implemented outside shaping (or even outside go-text).
Notice that I've written this PR to be entirely backward compatible. 
As a result, `SplitByFontGlyphs` and `SplitByFace` are somewhat redundant. We could remove `SplitByFontGlyphs` and expose the `fixedFontmap` type, as you wish.

[shaping] add a hook for a general face selection

---

go.mod
go.sum

Eliminates a panic that can be triggered by language tag parsing.
https://deps.dev/advisory/OSV/GO-2021-0113
Signed-off-by: Chris Waldon <christopher.waldon.dev@gmail.com>

deps: update golang.org/x/text

---

shaping/output_test.go

Go 1.19 refuses to run the tests with this mistake in place.

shaping: fix invalid use of errors.As

---

shaping/wrapping.go
shaping/wrapping_test.go

This is a small suggestion to clean up a bit the `breakOption` type and `Segmenter` usage.
In particular, it stores the `Segmenter` on the `LineWrapper`, so that memory can be reused if the same `LineWrapper` is itself reused for several paragraphs.

shaping: cleanup breakOption and cache the segmenter

---

shaping/wrapping.go
shaping/wrapping_test.go

I discovered that our logic to prevent splitting harfbuzz clusters during wrapping only worked if the run in consideration was at the beginning of the shaped text. A Gio fuzz test for rune accounting was failing as a result. I've fixed the logic and added a new test case to exercise the non-zero-offset cluster splitting case.
Signed-off-by: Chris Waldon <christopher.waldon.dev@gmail.com>

shaping: fix and test cluster splitting bug

---

shaping/output.go
shaping/shaper.go

This commit copies the shaping.Input's size to the corresponding shaping.Output. This makes shaping text with variable-sized runs much easier, as you don't need to do manual tracking of the run sizes.
Signed-off-by: Chris Waldon <christopher.waldon.dev@gmail.com>

shaping: provide size in output

---

shaping/fuzz_test.go

Go 1.16 (and earlier?) won't work without the old comment version

Fix old go mod vendor

---

CODEOWNERS

This file should ensure that the three listed people are requested for review on every PR, and I think we can combine it with branch protection rules to enforce that at least one of these three people must approve, though I'm not sure if we can enforce requiring two.
This is my attempt to move us closer to the policy described [here](https://github.com/go-text/typesetting/discussions/36).

codeowners: define code owners for main branch

---

.github/workflows/analysis.yml
harfbuzz/shaper_perf_test.go
segmenter/segmenter_test.go
shaping/output_test.go

Just a version bump for the linter and some adaptations to newer lint rules.

ci: update to latest staticcheck

---

shaping/wrapping.go

I'm working to implement the insertion of a text truncation symbol, and I've found the wrapping algorithm to be quite difficult to read (it's long, it's intricate, etc). These commits are an effort to make the core algorithm clearer, and to provide reusable helpers. There's definitely more that can be done here, but I thought these changes made a dent, and are probably not contentious.

Wrapping Refactors

---

harfbuzz/buffer.go
harfbuzz/shape.go

Move plan cache to the buffer object so we don't leak if the shaper / font is not needed any more
Fixes #47

Fix leak if fonts are replaced in usage

---

shaping/fuzz_test.go
shaping/wrapping.go
shaping/wrapping_test.go

This commit builds upon #44 to actually implement a text truncator symbol.
Some design choices:
- I tried to implement what we discussed in #28 towards the end of the thread.
- The `Truncator` is a single `Output`. This limits it to being a single font face, size, script, and language, though it can contain any number of glyphs. Supporting a `[]Output` truncator is a solid complexity hike, and I'm not sure that they are really used in practice.
- To make it easier to populate the `Truncator` field, I've provided a helper on `WrapConfig` that accepts a `Shaper` and `Input`.
- Applications often want to know how much of the string was truncated. I've made this an additional return value from the wrapping functions because I didn't see a clearer way to communicate it right now.
Only the …

Truncator support

---

shaping/wrapping.go
shaping/wrapping_test.go

This commit enables application code to require the truncator to be inserted when the text wraps to the maximum number of lines even when the text would normally fit without truncation. Our API is paragraph-centric, and thus does not know about paragraphs after itself. If trying to display truncatable text with multiple paragraphs of contents, the previous API could not display a truncator if the text wrapped a non-final paragraph to exactly fill the maximum number of lines. This would result in the text not appearing to be truncated, while it is missing entire lines of content.
The only reasonable solution I could see was to offer the option to always insert the truncator when wrapping the final line. Application code can then track whether there are future paragraphs (via readahead) and …

shaping: allow forcing truncation

---

shaping/lru.go
shaping/shaper.go
shaping/shaping_test.go

This commit restructures the font cache within the HarfbuzzShaper type to function as an LRU cache with a configurable size, and it also updates the shaping benchmark to measure the performance impact of the cache. For small bodies of text, initial benchmark results suggest substantial performance improvements for complex scripts (and complex fonts) and marginal gains for simpler scripts like latin.
```
$ go test -run '^$' -bench Shaping -benchmem ./shaping/ goos: linux
goarch: amd64
pkg: github.com/go-text/typesetting/shaping
cpu: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
BenchmarkShaping/10runes-arabic-0fontCache-8                7610            152486 ns/op           70570 B/op       1363 allocs/op
BenchmarkShaping/10runes-arabic-5fontCache-8               40285             29687 ns/op …
```

shaping: add lru font cache and benchmark impact

---

opentype/api/cmap.go
opentype/api/font/font.go
opentype/api/metadata/aspect.go
opentype/api/metadata/descriptor.go
opentype/api/metadata/descriptor_test.go
opentype/tables/head_gen.go
opentype/tables/head_src.go
opentype/tables/name_src.go
opentype/tables/name_test.go
opentype/tables/tables.go

This PR provides a way to query metadata about a font (see also #49)
The changes are large because some code has moved to the `tables` package to avoid duplication.
The various constants are taken from the CSS specifications (also used by other librairies like font-kit).
For now, the API requires a `*loader.Loader`,  meaning the original font file is needed. This is required since the `*font.Font` type does not store all the metadata, it only selects the shaping/glyph related information.

Add an API to query font metadata such as family name and style

---

opentype/api/font/renderer.go

sbix.glyphData and bitmap.glyphData get called repeatedly even for fonts that have neither. Previously, they allocated an error on each call.

Reuse errors in functions that get called a lot

---

opentype/api/font/renderer.go
opentype/api/font/renderer_test.go

Low hanging fruit in some performance.
The out slice was reallocated several times, we can use the length of contour points as a quick guess.
```
│ before.txt~ │             after.txt~              │
│   sec/op    │   sec/op     vs base                │
BuildSegments-32   2.435µ ± 4%   1.367µ ± 2%  -43.87% (p=0.000 n=10)
│ before.txt~  │              after.txt~              │
│     B/op     │     B/op      vs base                │
BuildSegments-32   3.484Ki ± 0%   1.750Ki ± 0%  -49.78% (p=0.000 n=10)
│ before.txt~ │             after.txt~             │
│  allocs/op  │ allocs/op   vs base                │
BuildSegments-32    7.000 ± 0%   1.000 ± 0%  -85.71% (p=0.000 n=10)
```

opentype/api/font: try to avoid extra allocations

---

shaping/fuzz_test.go
shaping/wrapping.go
shaping/wrapping_test.go

This PR is part of my ongoing effort to refactor the line wrapper with the goal of making it both easier to understand and able to support additional features.
We've long discussed wanting to be able to make text shaping an incremental process instead of having to do it all up front. Having and API that works in terms of iterators makes that much easier. As such, I've restructured the line wrapper to consume an iterator API that is expected to provide shaped text. I've only implemented an iterator backed by a pre-shaped slice for now, but it shouldn't be terribly hard to implement a lazy-shaping iterator with a compatible API.
However, introducing an iterator complicated some shaping operations and triggered some extra allocations (we couldn't just reach into the slice storage of the …

Use an iterator-style API to consume shaped text in line wrapper

---

shaping/fuzz_test.go
shaping/wrapping.go
shaping/wrapping_test.go

This commit implements wrapping on grapheme cluster boundaries (UAX#29) in addition to our previous word boundary (UAX#14) wrapping. The choice of whether to wrap on grapheme clusters is left up to a new LineBreakPolicy type with three options:
- WhenNecessary: This option will break using grapheme clusters when no word can fit on the line or when it is truncating a word (preserving as many grapheme clusters of the word as possible). This is the default policy.
- Always: This option will break on grapheme clusters whenever possible, fitting as many grapheme clusters as possible on every line.
- Never: This option disables the use of grapheme cluster breaking entirely, and preserves the prior behavior.
As WhenNecessary is the zero value of LineBreakPolicy, consumers of our API will …

Enable breaking lines within "words" by breaking on grapheme clusters

---

harfbuzz/harfbuzz_shape_input_test.go
language/scripts.go
language/scripts_test.go

This PR enables Harfbuzz tests for macos fonts to run (one test is using 'hebrew' instead of 'hebr' as script tag). See also https://github.com/go-text/typesetting-utils/pull/12 for more context.
Should have been included in #77, sorry for the oversight.

Harfbuzz tests

---

fontscan/fontmap.go
fontscan/footprint.go

~This commit allows already-parsed fonts to be inserted into the fontmap from an application. In order to do this with valid rune coverage maps, I needed to export a way for applications to construct Footprints so that the footprint could be provided alongside the font (assuming that the loader is no longer available). I'm open to feedback on whether this is a good idea.~
~@benoitkugler I found that Gio needed a means of registering already-parsed fonts (loaded from embedded font files) into the fontmap, so this is my stab at making that work. Let me know what you think about the approach.~
I've rewritten this to avoid exposing implementation details. Now there's simply an `AddFace` method that inserts an existing face and its metadata.
Gio uses this to register already-in-memory fonts so …

fontscan: expose footprint and means of registering existing faces

---

fontscan/footprint.go
opentype/api/font/font.go
opentype/api/metadata/aspect.go
opentype/api/metadata/descriptor.go

Providing a buffer for metadata extractions reduces allocation during system fonts scan.
The API change is required to make sure we don't keep a reference on the shared buffer (whose content may have been overwritten before resolving the family and aspect).

Reduce allocations in metadata

---

shaping/shaper.go

The `Glyph.RunesCount` property for vertical text was always 0, since `countClusters` was not handling vertical directions.
Besides, the `Progression` type makes the fix trivial, thanks for this idea !

[shaping] properly count clusters for vertical text

---

fontscan/fontmap.go
fontscan/fontmap_test.go

This PR fixes a couple of small problems I've encountered with the fontscan API:
- If given an empty slice for queried font families, it used fail to find anything
- If we reached the "arbitrary face" return logic, we iterated over a map and returned a random face each iteration

Fontscan fixes

---

opentype/api/font/renderer.go

This call to fmt.Errorf is a significant hotspot on Gio's shaping benchmarks. Using a concrete error type makes instantiating this error much cheaper and defers any acutal string formatting until when/if the error is printed.

opentype/api/font: use concrete error instead of fmt.Errorf

---

fontscan/fontconfig.go
fontscan/fontmap.go
fontscan/scan.go
fontscan/scandir_go1.16.go
fontscan/scandir_old.go

This allows client applications to substitute different logging libraries than simply the stdlib by implementing an adapter that conforms to this interface.

fontscan: use interface for logger

---

shaping/wrapping.go
shaping/wrapping_test.go

This commit ensures that we properly handle wrapping the empty string even when we have zero width to work with. It's common for application code to shape+wrap an empty string to get line metrics, and sometimes they may do that with zero width because the empty string needs no width. However, a faulty comparison in our logic for handling the empty string would fail because 0 is not less than 0. I've added tests triggering the problem and fixed the comparison logic.

shaping: fix empty string wrapping with width zero

---

shaping/output.go
shaping/wrapping.go
shaping/wrapping_test.go

Following the discussion on #90 , this is a try at better handling trailing spaces.
This is not complete (tests are not event passing), but I would be interested in early feedback.
One of the difficulty is about handling truncation properly :
I think the behavior should be, for a width of 5, to truncate
`quick_fox`
to 
`quick_...` (but with a zero advance space)
and not to 
`quick...`

Better space handling ?

---

fontscan/fontmap.go
fontscan/fontmap_test.go
fontscan/footprint.go
fontscan/match.go
fontscan/match_test.go
fontscan/substitutions.go
fontscan/substitutions_test.go

This PR alters the way we perform family substitutions when looking for a fallback font, by applying them to the whole family list of the user query, so that substitution priorities are better respected.
Let me illustrate the change on the following example, where an user queries `{CustomWeirdFont, Helvetica}`, on a system with neither `CustomWeirdFont` nor `Helvetica`, and calls `ResolveFace('a')`
No exact match occurs (step 1), so we apply substitutions (step 2). `CustomWeirdFont` is unknown from the library rules, so it is expanded by default to `sans-serif` for which the system has (many) fonts (with support for the rune 'a'). So `ResolveFace` returns the 'preferred' `sans-serif` face. It has not take into account the `Helvetica` substitutions.
We still look for an exact match, in the …

[fontscan] Better family substitutions

---

harfbuzz/ot_arabic.go
harfbuzz/ot_kern.go
harfbuzz/ot_layout_gsubgpos.go
harfbuzz/ot_map.go

This makes `Buffer` more memory efficient when reusing the same font, since the `otMap` is stored on the buffer `planCache` .

[harfbuzz] reuse otApplyContext instead of allocating a new one

---

go.mod
go.sum
opentype/api/metadata/descriptor.go
opentype/api/metadata/descriptor_test.go

Previous to this change, we were not using the 'OS/2' table when computing the `Aspect` of a font. 
It is actually an outstanding issue, but it went undetected since the fallback `inferFromStyle` was doing a pretty good job. 
However, there is (at least) one font (DejaVu Sans) which has different values for its weight (that is, the OS/2 and style string values do not match). In this case, it is better to give priority to the 'OS/2' table (at least, that is what fontconfig does).
Also, I've added the font file in the merged https://github.com/go-text/typesetting-utils/pull/14 PR.

[opentype/metadata] Fix aspect resolution

---

fontscan/fontmap.go
fontscan/fontmap_test.go

CSS [@font-face rule](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face) allows a document author to query a system (or local) font by _family name_. Although similar to the functionnality `SetQuery` and `ResolveFace` are providing, this is a different task (no rune involved, no aspect involved, only the system fonts are used).  Also, no fallback is desirable.
This PR then provides a `FindSystemFont(family string)` (its implementation is rather simple with our internal index).

[fontscan] Expose a way to query a system font by family

---

shaping/wrapping.go
shaping/wrapping_test.go

This PR also returns the internal value used by the line wrapper, which is somewhat annoying to compute, but very useful when processing a text line by line.

[shaping/wrapper] return the index of the next line in WrapLine

---

harfbuzz/ot_layout_gpos.go
opentype/tables/ot_properties.go

During some benchmarks, I found `tables.PairSet.FindGlyph` was a really high source of heap allocations.
Using a plain struct (probably) allows the compiler/runtime to allocate it on the stack, resulting in a sizable reduction of heap allocations.

[opentype/gpos] use plain struct instead of pointer

---

opentype/api/font/cff/charstring.go
opentype/api/font/cff/parser_test.go

This PR fixes #122.
The 'blend' operator needs to skip its arguments, even if the user has not selected any variations.

Fix CFF2 parsing

---

fontscan/fontmap.go
fontscan/fontmap_test.go
fontscan/footprint.go

Let the user choose the `Location` when adding a Face (for #112).

[fontscan] Specify Location in AddFace

---

harfbuzz/fonts.go
harfbuzz/harfbuzz_shape_test.go

Previously, the user provided Size factor was not applied to the offsets.
This is particularly visible for vertical texts (the bug was found working on #124).

[harfbuzz] Properly scale glyph X and Y offsets

---

shaping/input.go
shaping/input_test.go

In `Segmenter.Split`, Inherited script must be handled like Common, to avoid creating more runs than required (which in turns does not allow harfbuzz to properly shape the whole text).
Fixes #127

[shaping] fix handling of Inherited script in Segmenter.Split

---

fontscan/fontmap.go

I wanted to get all of the font locations that matched a given font family.
This PR adds such a function.

fontscan: add function to return all matched font locations

---

README.md

As discussed on Slack, I've added a small note about breaking changes and  v0.x.y versions.
This should be tagged as v0.1.0. 
This also implies we will regularly group commits into tagged versions, fixing #99

Update README.md about breaking changes

---

.github/workflows/analysis.yml
.github/workflows/test.yml

This updates the CI infrastructure to be more modern and up to date with my latest changes over at Fyne.
Some highlights:
- Stricter permissions for security reasons.
- Update checkout action for deprecation and security reasons.
- Faster setup of the Go toolchain.
- Tests no run with Go 1.17 as base (as `go.mod` specifies).
- All workflows run on newer Go versions.
- Latest version of staticcheck.
I also fixed some broken logic in the test workflow.

Update CI workflows to better match latest changes in Fyne

---

shaping/wrapping_test.go

Reassigning a global variable is bold..

[shaping/test] do not reassign text input, closes #136

---

go.mod
go.sum
harfbuzz/fonts_test.go
opentype/api/font/ot_layout.go

It seems some fonts have corrupted LangSys entries. This commit ignores out of range feature indices. 
For #140

[opentype] sanitize invalid LangSys entries in GSUB/GPOS tables

---

fontscan/footprint.go

This is for #144 , thank you @dominikh for the suggested fix. 
Note that we still do a little bit more than strictly needed, since `NewLoaders` read all the face _headers_. But, since parsing the header of a font is really nothing compared to parsing its tables, I think this is enough.

[fontscan] only load the required face in font collections

---

shaping/input.go
shaping/input_test.go

This commit ensures that strings of only whitespace runes (and other ignorable runes for the purposes of face selection) are actually assigned a face at all. The prior code could accidentally leave the face nil for inputs of all whitespace, resulting in unexpected line metrics for the whitespace.
I'd like to cherry pick this onto v0.1.0 to create v0.1.1. That's why this changeset is based on v0.1.0 instead of main.

shaping: ensure all-whitespace strings are assigned a face

---

font/cache.go
font/font.go
font/glyphs.go
font/metrics.go
font/renderer.go
font/renderer_test.go
font/variations.go
font/variations_test.go
fontscan/fontmap_test.go
fontscan/footprint.go
harfbuzz/fonts.go
harfbuzz/fonts_test.go
harfbuzz/harbuzz_test.go
harfbuzz/harfbuzz_shape_test.go
harfbuzz/ot_layout_gpos.go
harfbuzz/shaper_perf_test.go
shaping/shaping_test.go

I've noticed typesetting shows somewhat poor performance when using fonts with CFF tables (usually marked with an .otf extension).
A quick benchmark revealed that the bottleneck is in the `[Face.GlyphExtents]` method, which is called (in `HarbuffShaper.Shape`) for every glyph.
Contrary to the 'glyf' table used in Truetype font files, CFF tables do not expose this metrics : we have to parse the whole glyph to compute it. 
The issue will also arise with variable fonts, for which we also have to apply the variations to the glyph description in order to compute its extents. 
Thus, I propose to add a cache for glyph extents to the `[Face]` struct. 
The following benchmark shows a net improvement for CFF tables (Raleway-v4020-Regular.otf) and variable fonts (Commissioner-VF.ttf#01). …

[font] Add a glyph extents cache

---

font/font.go
font/metadata.go
font/opentype/tables/head_src.go
font/variations_test.go

When you want to process a font file, you have to parse the 'head' table first. The issue is that some macos bitmap fonts use the 'bhed' table instead.
We use an helper function `loadHeadTable` to handle this complexity. It may be used by libraries which want to manually inspect a font file, but it was hidden in #130 by mistake.
This PR fixes the issue and exposes this helper back.
This is backward compatible, with no changes for GUI toolkits end users.

[font] expose LoadHeadTable

---

harfbuzz/ot_shaper.go
harfbuzz/shape.go

This is a memory optimization : previously, the `shaper` field (with type `*shaperOpentype`) was allocated at each `harbuzz.Shape` call.
Removing the pointer and simply resetting the fields instead reduces memory usage. 
This is very similar to https://github.com/go-text/typesetting/pull/106

[harfbuzz] reuse shaperOpentype instead of allocating a new one

---

shaping/wrapping.go
shaping/wrapping_test.go

Due to a missing reference operator (&), the trailing whitespaces were not collapsed properly.
An interesting side effect of this change was to discover that some tests used one `Output` several times, without copying its glyphs, leading to spurious errors when the glyphs were mutated.

[shaping] Trailing spaces

---

shaping/output.go
shaping/spacing.go
shaping/spacing_test.go
shaping/wrapping.go
shaping/wrapping_test.go

This is a revisited version of #90. 
The proposed API consists of two methods `Output.AddWordSpacing()` and `Output.AddLetterSpacing()` and a convenient function `AddSpacing` accepting a slice of `Output`s.
I've exported the `Output` methods so that it may be used by external implementation of `RunIterator`.
Implementation note : by registering the letter spacing in a new `Glyph` field, the line wrapper is able to trim edge spacing on its own, without requiring the user to "clean up" the runs after wrapping. 
What do you think ?

[shaping] add support for custom letter and word spacing

---

font/font_test.go
font/metrics.go
shaping/spacing.go

This PR adds a fallback required to retrieve cap-height and x-height values for older fonts (having a 'OS/2'  table with version older than 2). 
(The implementation follows x/image/font and harfbuzz references.)
For #169.

Cap height fallback

---

font/metadata_test.go
font/opentype/tables/name_src.go
font/opentype/tables/name_test.go
fontscan/serialize.go
go.mod
go.sum

Some Windows fonts use UTF-16 encoding for their family names : we were missing some of them when decoding the 'name' table.
This a fix for #172 (and should also fix #171).
I've also updated the fontscan cache version, to ensure the existing footprints will be properly updated.
@akiyosi Could you confirm this fix resolves your initial issue ? Thank you !

[font] Names decoding

---

shaping/output.go
shaping/output_test.go
shaping/wrapping.go
shaping/wrapping_test.go

Our previous implementation of trimming the whitespace off of the end of wrapped lines assumed that the end was always the final logical run, and that the final glyph within that run was visually last. Neither of these assumptions are true in real-world bidi text. The final logical run may be embedded wtihin the center of the visual line of text, and sometimes the final glyph is the first within a run, rather than the last.

shaping: (wrapping) make whitespace trim bidi-aware

---

shaping/wrapping.go
shaping/wrapping_test.go

This commit fixes an oversight in our handling of text truncators. They were inserted into the text *after* bidi run reordering had already occurred, which would place them in the wrong visual position sometimes. Additionally, their rune data reflected the runes of the truncator string instead of the runes of text the truncator represents, but it is clearly more desirable for the truncator to stand in for all of the text it replaces.
This commit does change the semantics of a truncator run's Range field in the output text. It will now describe the replaced range of text. This does greatly simplify consuming the shaped text data, as you can see by how it simplified the tests. We don't have to factor out the truncator or do extra math to make sure all runes are accounted for. Instead, the …

shaping: treat truncator as proper run for bidi and rune counting

---

font/opentype/tables/glyphs_glyf_src.go
shaping/wrapping.go

these allow:
1. nonstandard output wrapping elements with no glyphs. we use this for math rendering, which creates a "dummy" output element for line wrapping purposes.
2. fonts without glyf table (metrics only). we use these for rendering on web platforms that use html canvas measure text but do not require glyf tables, so the font files can be smaller.

two nil guards that we need
